### ISSUE TITLE
Update a shopcart resource

### ISSUE THREAD

**Issue by apoorvsingh2000** [CSCI-GA-2820-FA24-003/shopcarts#11]
**As a** customer
**I need** I need to be able to update my shopcart by specifying the customerID,
**So that** I can update my shopcart by adding or removing products etc.
   
 ### Details and Assumptions
The customer has an active shopcart associated with their customer ID.
The customer ID is a valid input.
API: `PUT    /shopcarts/{id}             <- Update a shopcart`

 ### Acceptance Criteria  
   
 ```gherkin
 Given that a customer has an active shopcart,
 When they want to update their shopcart with a valid customer ID,
 Then their respective shopcart gets updated.
```

**Comment by safipatel** [comment]
Ziyan pdf:
[Update.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWMzQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e400cb31fa1869be5450f8ee73209ac1c3c0b48b/Update.pdf)

**Comment by ZylMjyFw** [comment]
- Updated the shopcart resource to handle item updates within the cart.
- Added test cases to verify resource updates (e.g., updating item quantity).
- PUT requests now update specific resources in the cart.

**Comment by ZylMjyFw** [comment]
"Implemented the PUT endpoint to update a shopcart resource based on customer ID (referred to as customer_name in the code)."
"Updated the routes.py to include the PUT /shopcarts/{id} endpoint. Modified the Shopcart model to support updating customer details and items. Added unit tests to cover this functionality."

**Comment by ZylMjyFw** [comment]
[https://github.com/CSCI-GA-2820-FA24-003/shopcarts/commit/a165229f0028eb4174f4918b567608c6305f7c6e](url)
