### ISSUE TITLE
Delete a shopcart resource

### ISSUE THREAD

**Issue by apoorvsingh2000** [CSCI-GA-2820-FA24-003/shopcarts#14]
**As a** customer
**I need** I need to be able to delete my shopcart by specifying the customerID,
**So that** I can delete my shopcart removing all products in it.
   
 ### Details and Assumptions
The customer has an active shopcart, with at least one item in it, associated with their customer ID.
The customer ID is a valid input.
API: `DELETE /shopcarts/{id}             <- Delete a shopcart`

 ### Acceptance Criteria  
   
 ```gherkin
 Given that a customer has an active shopcart with at least one item in it,
 When they want to delete their shopcart,
 Then their respective shopcart gets deleted from the database.
```

**Comment by ZylMjyFw** [comment]
"Created DELETE endpoint for removing a shopcart resource based on customer ID (customer_name)."
"Added DELETE /shopcarts/{id} endpoint to remove the shopcart from the database. Unit tests are implemented to ensure proper functionality."
