### ISSUE TITLE
Remove Item from Shopcart

### ISSUE THREAD

**Issue by yuhao0308** [CSCI-GA-2820-FA24-003/shopcarts#2]
As a customer,
I need to be able to remove an item from my shopcart using the product ID,
So that I can manage the products I no longer want to purchase.

Assumptions:
- The customer has at least one product in the shopcart.
- The product ID provided exists in the shopcart.
- API endpoint: `DELETE /shopcarts/{id}/items/{id}  <- Delete an item from a shopcart`

Acceptance Criteria:
```
Given that the product exists in the shopcart,
When the customer requests to remove it using its product ID,
Then the product is removed, and the cart reflects the updated contents.

Given that the product does not exist in the shopcart,
When the customer attempts to remove the product,
Then an error message is returned stating that the product is not found.
```

**Comment by safipatel** [comment]
Added corresponding API endpoint for clarity
