### ISSUE TITLE
View Shopcart Contents

### ISSUE THREAD

**Issue by yuhao0308** [CSCI-GA-2820-FA24-003/shopcarts#3]
As a customer,
I need to be able to view all the items currently in my shopcart, including the product ID, product description, quantity, and price,
So that I can review what I am planning to purchase before checking out.

Assumptions:
- The customer has an active shopcart associated with their customer ID.
- The shopcart has valid product details such as ID, description, quantity, and price.
- API: ` GET    /shopcarts/{id}/items       <- List all items in a shopcart`

Acceptance Criteria:
```
Given that the customer has an active shopcart,
When they request to view the shopcart,
Then the system returns all items in the shopcart, including product ID, description, quantity, and price.

Given that the customer has no items in the shopcart,
When they request to view the cart,
Then an empty list is returned, and the total price is displayed as zero.
```

**Comment by safipatel** [comment]
Added corresponding API endpoint for clarity
