### ISSUE TITLE
Update Item in Shopcart

### ISSUE THREAD

**Issue by apoorvsingh2000** [CSCI-GA-2820-FA24-003/shopcarts#4]
As a customer,
I need to be able to update a product in my shopcart by specifying the product ID, quantity, and product description,
So that I can update the product(s) type, quantity, type etc. I wish to update the products from the cart itself.

Assumptions:

The customer has an active shopcart associated with their customer ID.
The product ID, description, and quantity are valid inputs.
API: `PUT    /shopcarts/{id}/items/{id}  <- Update an item in a shopcart`
   
 ### Acceptance Criteria  
   
 ```
Given that a customer has an active shopcart,
When they update a product with a valid product ID, description, and quantity,
Then the product is updated in the shopcart, and the shopcart reflects the new product type, quantity etc.
 
Given that a product is already in the cart,
When the customer adds the same product,
Then the quantity of the product is updated in the shopcart.
```

**Comment by safipatel** [comment]
Added corresponding API for clarity
