### ISSUE TITLE
List a customer's Shopcart <Admin>

### ISSUE THREAD

**Issue by apoorvsingh2000** [CSCI-GA-2820-FA24-003/shopcarts#5]
As a Shopcart admin,
I need to be able to view all the products in any customer's shopcart by specifying the customer ID.
So that I can collect data on the products that are in demand.

Assumptions:
- The customer has an active shopcart associated with their customer ID.
- The customer ID is a valid input.

Acceptance Criteria:
```
Given that a customer has an active shopcart,
When they add a product with a valid product ID, description, and quantity,
Then the product is visible to the admin in the customer's shopcart, and the shopcart reflects the new product in the admin portal.

```

**Comment by safipatel** [comment]
The idea is to have both options, where you can list all shopcart for an admin and also view your current shopcart.
I don't think this is a lower priority, additional feature for later.

**Comment by safipatel** [comment]
While I see this as a feature that an actual "customer" would never see (in the sense of a customer of our business that uses a shopcart), I think the **customer** we care about is in the agile sense of the **customer** of our product. So in that sense, I would argue that an admin account on the Shopcart website who has a job of customer service, etc. would still be considered a **customer of our product**, making this an **enhancement** and **not technical debt.**
